import { EmptyState } from "@nen/ui";
import { BookCard, BookCover } from "../components/BookCard";
import { AppLink } from "../components/Link";
import { collections } from "../data/collections";
import { getSimilarBooks } from "../domain/books/similarity";
import type { Book } from "../domain/books/types";
import { useSeo } from "../hooks/useSeo";

const readingLabels={independent:"Для самостоятельного чтения",together:"Для чтения со взрослым",both:"Можно читать самостоятельно или вместе"};
export function BookDetailPage({ slug,books,favorites,toggleFavorite,navigate }:{slug:string;books:Book[];favorites:string[];toggleFavorite:(id:string)=>void;navigate:(path:string)=>void}) {
  const book=books.find((item)=>item.slug===slug); useSeo(book?`${book.title} — книга для детей | НЭН`:"Книга не найдена — НЭН",book?.shortDescription??"Книга не найдена.",book?`/books/${book.slug}`:"/books");
  if(!book)return <section className="page"><EmptyState title="Книга не найдена" action={<button className="primary-button" onClick={()=>navigate("/books")}>В каталог</button>}><p>Возможно, ссылка устарела или запись пока не опубликована.</p></EmptyState></section>;
  const similar=getSimilarBooks(book,books,4); const included=collections.filter((collection)=>collection.bookIds.includes(book.id));
  return <><section className="detail-page"><nav className="breadcrumbs" aria-label="Хлебные крошки"><AppLink href="/books" navigate={navigate}>Каталог</AppLink><span>/</span><span>{book.title}</span></nav><div className="detail-hero"><div className="detail-cover"><BookCover book={book} large/><button className={`save-large${favorites.includes(book.id)?" active":""}`} onClick={()=>toggleFavorite(book.id)} aria-pressed={favorites.includes(book.id)}>{favorites.includes(book.id)?"В избранном":"Сохранить в избранное"}</button></div><div><p className="eyebrow">Рекомендация НЭН · {book.ageLabel}</p><h1>{book.title}</h1>{book.originalTitle&&<p className="original-title">{book.originalTitle}</p>}<p className="detail-author">{book.author}</p><p className="detail-lead">{book.shortDescription}</p><div className="detail-why"><small>Почему рекомендуем</small><p>{book.whyRecommended}</p></div><dl className="quick-facts"><div><dt>Как читать</dt><dd>{readingLabels[book.readingMode]}</dd></div>{(book.lengthLabel||book.pages)&&<div><dt>Объём</dt><dd>{book.lengthLabel??`${book.pages} страниц`}{book.pages&&book.lengthLabel?` · ${book.pages} стр.`:""}</dd></div>}{book.languageDifficulty&&<div><dt>Сложность языка</dt><dd>{{easy:"простой",medium:"средний",advanced:"сложный"}[book.languageDifficulty]}</dd></div>}</dl></div></div></section>
    <section className="detail-info"><div><h2>О книге</h2>{book.fullDescription&&book.fullDescription!==book.shortDescription?<p>{book.fullDescription}</p>:<p>{book.shortDescription}</p>}</div><div className="detail-sidebar">{book.themes.length>0&&<Fact title="Темы" values={book.themes}/>} {book.genres.length>0&&<Fact title="Жанры" values={book.genres}/>} {book.moods.length>0&&<Fact title="Настроение" values={book.moods}/>} {book.sensitiveTopics.length>0&&<Fact title="Чувствительные темы" values={book.sensitiveTopics}/>} {book.officialAgeRating&&book.officialAgeRatingSource&&<div><h3>Официальный рейтинг</h3><p>{book.officialAgeRating}</p><a href={book.officialAgeRatingSource} target="_blank" rel="noreferrer">Источник</a></div>}</div></section>
    {included.length>0&&<section className="section"><header className="section-heading"><h2>В подборках НЭН</h2></header><div className="inline-collections">{included.map((collection)=><AppLink key={collection.slug} href={`/collections/${collection.slug}`} navigate={navigate}>{collection.title}<span>{collection.description}</span></AppLink>)}</div></section>}
    {similar.length>0&&<section className="section section--white"><header className="section-heading"><div><p className="eyebrow">Похожий возраст и темы</p><h2>Похожие книги</h2></div></header><div className="book-grid">{similar.map(({book:other,reasons})=><div key={other.id}><BookCard book={other} favorite={favorites.includes(other.id)} toggleFavorite={()=>toggleFavorite(other.id)} navigate={navigate} compact/><p className="similar-reason">Почему похожа: {reasons.slice(0,2).join(", ")}.</p></div>)}</div></section>}
  </>;
}
function Fact({title,values}:{title:string;values:string[]}){return <div><h3>{title}</h3><div className="tag-row">{values.map((value)=><span key={value}>{value}</span>)}</div></div>}
