import { useMemo, useState } from "react";
import { BookCard } from "../components/BookCard";
import type { Book, BookFilters, ReadingMode } from "../domain/books/types";
import { emptyFilters, searchBooks } from "../domain/books/filters";
import { useSeo } from "../hooks/useSeo";

const situations=["хочет отдохнуть","тревожится","грустит","скучает","хочет посмеяться","узнать что-то новое"];
const situationMoods:Record<string,string[]>={"хочет отдохнуть":["спокойное","уютное"],"тревожится":["спокойное","поддерживающее"],"грустит":["трогательное","поддерживающее"],"скучает":["захватывающее","смешное"],"хочет посмеяться":["смешное"],"узнать что-то новое":["познавательное"]};
export function RecommendPage({books,favorites,toggleFavorite,navigate}:{books:Book[];favorites:string[];toggleFavorite:(id:string)=>void;navigate:(path:string)=>void}){
  useSeo("Умный подбор книг НЭН","Ответьте на несколько вопросов и получите объясненные книжные рекомендации.","/recommend");
  const [age,setAge]=useState(6);const [reading,setReading]=useState<ReadingMode>("together");const [situation,setSituation]=useState("");const [theme,setTheme]=useState("");const [step,setStep]=useState(1);const themes=useMemo(()=>[...new Set(books.flatMap((book)=>book.themes))].slice(0,12),[books]);
  const filters:BookFilters={...emptyFilters,age,reading,themes:theme?[theme]:[],moods:situation?situationMoods[situation]??[]:[]};const result=searchBooks(books,filters);const ranked=(result.exact.length?result.exact:result.nearby).slice(0,6);
  const restart=()=>{setAge(6);setReading("together");setSituation("");setTheme("");setStep(1)};
  return <section className="recommend-page"><header><p className="eyebrow">Умный подбор НЭН</p><h1>Найдём книгу для вашего вечера</h1><p>Это подбор по редакционным правилам и данным каталога, а не ответ искусственного интеллекта.</p><div className="progress" aria-label={`Шаг ${step} из 4`}><span style={{width:`${step*25}%`}}/></div></header>{step<4?<div className="wizard-card">{step===1&&<><small>Шаг 1 из 3</small><h2>Сколько лет ребёнку?</h2><div className="age-picker"><button onClick={()=>setAge(Math.max(2,age-1))} aria-label="Уменьшить возраст">−</button><output>{age}<span>лет</span></output><button onClick={()=>setAge(Math.min(14,age+1))} aria-label="Увеличить возраст">+</button></div></>}{step===2&&<><small>Шаг 2 из 3</small><h2>Как планируете читать?</h2><div className="option-cards">{[["together","Вместе со взрослым"],["independent","Ребёнок сам"],["both","По-разному"]].map(([value,label])=><button key={value} className={reading===value?"selected":""} onClick={()=>setReading(value as ReadingMode)}>{label}</button>)}</div></>}{step===3&&<><small>Шаг 3 из 3</small><h2>Что сейчас особенно важно?</h2><div className="chips large">{situations.map((value)=><button key={value} className={situation===value?"selected":""} onClick={()=>setSituation(value)}>{value}</button>)}</div><h3>Интерес ребёнка</h3><div className="chips">{themes.map((value)=><button key={value} className={theme===value?"selected":""} onClick={()=>setTheme(value)}>{value}</button>)}</div></>}<div className="wizard-actions">{step>1&&<button className="secondary-button" onClick={()=>setStep(step-1)}>Назад</button>}<button className="primary-button" onClick={()=>setStep(step+1)}>{step===3?"Получить рекомендации":"Дальше"}</button></div></div>:<div className="recommend-results"><div className="recommend-summary"><p className="eyebrow">Нашли {ranked.length} вариантов</p><h2>{result.exact.length?"Подходящие книги":"Ближайшие рекомендации"}</h2><p>Для ребёнка {age} лет мы ищем {reading==="independent"?"книги для самостоятельного чтения":"книги для чтения вместе"}{theme?`, с темой «${theme}»`:""}{situation?`, когда он ${situation}`:""}. {result.explanation}</p><div><button className="secondary-button" onClick={()=>setStep(1)}>Уточнить ответы</button><button className="text-button" onClick={restart}>Начать заново</button></div></div><div className="book-grid">{ranked.map((item)=><BookCard key={item.book.id} book={item.book} ranked={!result.exact.length?item:undefined} favorite={favorites.includes(item.book.id)} toggleFavorite={()=>toggleFavorite(item.book.id)} navigate={navigate}/>)}</div></div>}</section>;
}
