import { Artwork, ContentCard, FavoriteButton } from "../components";
import { contentItems, confirmedOfficialRating } from "../lib/content";
import { useSeo } from "../hooks/useSeo";
import type { AppContentType } from "../types";

export function DetailPage({ type, slug, favorites, toggle, navigate }: { type?: AppContentType; slug: string; favorites: string[]; toggle: (id: string) => void; navigate: (path: string) => void }) {
  const item = contentItems.find((entry) => entry.slug === slug && (!type || entry.type === type));
  useSeo(item ? `${item.title} — ${item.type === "book" ? "книга" : item.type === "cartoon" ? "мультфильм" : "фильм"} | НЭН` : "Произведение не найдено — НЭН", item?.description ?? "Каталоги НЭН.", item ? `/${item.type === "book" ? "books" : item.type === "cartoon" ? "cartoons" : "movies"}/${item.slug}` : "/");
  if (!item) return <section className="section"><h1>Произведение не найдено</h1><button onClick={() => navigate("/")}>На главную</button></section>;
  const section = item.type === "book" ? "books" : item.type === "cartoon" ? "cartoons" : "movies";
  const sectionTitle = item.type === "book" ? "Книги" : item.type === "cartoon" ? "Мультфильмы" : "Фильмы";
  const officialRating = confirmedOfficialRating(item.source);
  const similar = contentItems.filter((candidate) => candidate.id !== item.id && candidate.type === item.type && candidate.themes.some((theme) => item.themes.includes(theme))).slice(0, 3);
  return <><section className="detail-hero"><div className="breadcrumbs"><button onClick={() => navigate("/")}>Главная</button><span>/</span><button onClick={() => navigate(`/${section}`)}>{sectionTitle}</button><span>/</span><span>{item.title}</span></div><div className="detail-grid"><Artwork item={item.source} large /><div className="detail-copy"><div className="eyebrow">{sectionTitle}</div><h1>{item.title}</h1>{item.originalTitle && <p className="original-title">{item.originalTitle}</p>}<p className="detail-lead">{item.description}</p>{item.source.editorialNote && <aside className="editorial-note"><div className="eyebrow">Почему рекомендует НЭН</div><p>{item.source.editorialNote}</p></aside>}<div className="detail-actions"><FavoriteButton active={favorites.includes(item.id)} onClick={() => toggle(item.id)} /><span>{favorites.includes(item.id) ? "В избранном" : "Сохранить на потом"}</span></div><dl><div><dt>Возрастная рекомендация НЭН</dt><dd>{item.nenAgeRecommendation.label}</dd></div>{officialRating && <div><dt>Официальная маркировка</dt><dd>{officialRating}</dd></div>}<div><dt>{item.type === "book" ? "Автор" : "Автор / режиссёр"}</dt><dd>{item.source.creator ?? "Не указано"}</dd></div>{item.source.studioOrPublisher && <div><dt>Студия / издательство</dt><dd>{item.source.studioOrPublisher}</dd></div>}<div><dt>Страна и год</dt><dd>{[item.country, item.year].filter(Boolean).join(", ") || "Не указано"}</dd></div><div><dt>{item.type === "book" ? "Объём" : "Длительность"}</dt><dd>{item.source.durationMinutes ? `${item.source.durationMinutes} минут` : item.source.pageCount ? `${item.source.pageCount} страниц` : item.source.durationCategory ?? "Не указано"}</dd></div></dl></div></div></section><section className="section facts"><div><div className="eyebrow">О произведении</div><h2>Что важно знать</h2></div><div className="fact-columns"><Fact title="Жанры" values={item.source.genres} /><Fact title="Темы" values={item.themes} /><Fact title="Настроение" values={item.moods} /><Fact title="Подойдёт" values={[item.source.suitableForBedtime ? "перед сном" : "", item.source.suitableForFamily ? "всей семьёй" : "", item.source.suitableForIndependentUse ? "самостоятельно" : ""].filter(Boolean)} /></div></section>{similar.length > 0 && <section className="section"><div className="eyebrow">Ещё варианты</div><h2>Похожее по теме</h2><div className="catalog-grid">{similar.map((candidate) => <ContentCard key={candidate.id} content={candidate} favorite={favorites.includes(candidate.id)} toggleFavorite={() => toggle(candidate.id)} navigate={navigate} />)}</div></section>}</>;
}

function Fact({ title, values }: { title: string; values: string[] }) { return <div><h3>{title}</h3><div className="tags">{values.length ? values.map((value) => <span key={value}>{value}</span>) : <span>не указано</span>}</div></div>; }
